resolver: lts-20.10

extra-deps:
  - url: https://github.com/codewars/hspec-formatters-codewars/archive/v0.3.0.tar.gz
  - url: https://github.com/codewars/hspec-codewars/archive/v0.1.0.tar.gz

# Control whether we use the GHC we find on the path
system-ghc: true
